name: Update some list

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Execute every week at 0:00 CST (UTC+8), which is 16:00 UTC on the previous day
    - cron: '23 18 * * *' # 每天 UTC 18:23 (北京时间次日凌晨 02:23)
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: some generator
        uses: ZSCGR/mawesome@v2.2.3-beta.1
        with:
          api-token: ${{ secrets.PERSONAL_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          template-path: "template/README.ejs"
          github-name: ${{ github.repository_owner }}
